### PR TITLE
add global wrapper class for VF pages

### PR DESCRIPTION
**Pull request by ghost**
As of version 2.0 of the SLDS the style will interfere with some of the classic styles found in the Salesfore Aloha theme. This can be prevented by wrapping all of the SLDS style in a global class. Once that global class name is set at the root DOM element of your Visualforce page the SLDS styles are then scoped to you custom code.

### CODE REVIEW

**Comment by ghost** [comment]
@msc654 slds has it's own global wrapper "slds". if you want some custom wrapper just add it in a root element.  as an example your root element can looks like this: <div class="slds custom-wrapper"></div>

**Comment by ghost** [comment]
Its the extra style libraries that are changing the style of the classic view. The wrapper class is not being applied to these: `"@import             \"~@salesforce-ux/design-system/scss/design-tokens\";\n"
    + "@import             \"~@salesforce-ux/design-system/scss/config\";\n"
    //path to slds images and fonts
    + "$static-image-path: \"~@salesforce-ux/design-system/assets/images/\";\n"
    + "$static-font-path:  \"~@salesforce-ux/design-system/assets/fonts/webfonts\";\n"
    //standard style components
    + "@import             \"~@salesforce-ux/design-system/scss/vendor/deprecate\";\n"
    + "@import             \"~@salesforce-ux/design-system/scss/dependencies/index\";\n"
    + "@import             \"~@salesforce-ux/design-system/scss/core/font\";\n"
    + "@import             \"~@salesforce-ux/design-system/scss/vendor/normalize\";\n"
    + "@import             \"~@salesforce-ux/design-system/scss/core/core\";\n";`

**Comment by ghost** [comment]
please try it. load a page with <div class="slds"></div> inside a vf page and you will see the background and logo is  effected in the classic view.

**Comment by dmitry-prohorov** [comment]
@msc654 thanks for your pull request, your changes were added to v0.0.3
in v0.0.4 I will adjust changes from latest slds release

**Pull request merged**
